spring:
  cloud:
    function:
      definition: allCommunity;photoContent;user;
    stream:
      bindings:
        photoContent-in-0:
          destination: community
        allCommunity-out-0:
          destination: allCommunity
        allCommunity-in-0:
          destination: allCommunity
        user-in-0:
          destination: community
      rabbit:
        bindings:
          photoContent-in-0:
            consumer:
              exchangeType: direct
              binding-routing-key: PhotoContent
          allCommunity-out-0:
            producer:
              exchangeType: direct
              routing-key: AllCommunity
          allCommunity-in-0:
            consumer:
              exchangeType: direct
              binding-routing-key: AllCommunity
          user-in-0:
            consumer:
              exchangeType: direct
              binding-routing-key: User
  rabbitmq:
    host: 52.79.143.36
    username: root

    password: root
    port: 5672
