spring:
  cloud:
    function:
      definition: photoContent;
    stream:
      bindings:
        photoContent-in-0:
          destination: community
      rabbit:
        bindings:
          photoContent-in-0:
            consumer:
              exchangeType: direct
              binding-routing-key: PhotoContent
  rabbitmq:
    host: 52.79.143.36
    username: root
    password: root
    port: 5672
