version: '3.8'
services:
  community:
    image: hobbyhobby/community:latest
    container_name: community
    ports:
      - "8083:8080"
    networks:
      dockernet:
        ipv4_address: 10.10.20.140
  photocontent:
    image: hobbyhobby/photocontent:latest
    container_name: photocontent
    ports:
      - "8082:8080"
    networks:
      dockernet:
        ipv4_address: 10.10.20.141
  textcontent:
    image: hobbyhobby/textcontent:latest
    container_name: textcontent
    ports:
      - "8081:8080"
    networks:
      dockernet:
        ipv4_address: 10.10.20.142
  user:
    image: hobbyhobby/user:latest
    container_name: user
    ports:
      - "8080:8080"
    networks:
      dockernet:
        ipv4_address: 10.10.20.143
  eureka:
    image: hobbyhobby/eureka:latest
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      dockernet:
        ipv4_address: 10.10.20.144
    environment:
      TZ: Asia/Seoul

  gateway:
    image: hobbyhobby/gateway:latest
    container_name: gateway
    ports:
      - "8000:8000"
    networks:
      dockernet:
        ipv4_address: 10.10.20.145
    environment:
      TZ: Asia/Seoul
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hobbyhobby
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  dockernet:
    external: true