server:
  port: 8000
jwt:
  accessSecretKey: a1c2c3e4s5s6s7e8c9r10e11t12k13e14y15h16o17b18b19y20h21o22b23b24y25
  accessExpirationSeconds: 3600
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.10.20.144:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            message: Spring Cloud Gateway GlobalFilter Message
            showPreLogger: true
            showPostLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/user/mypage, /user-service/api/user/delete
          filters:
            - CustomFilter
            - LoggingFilter
            - AuthorizationHeaderFilter
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=
            - **
          filters:
            - CustomFilter
            - LoggingFilter
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: textcontent-service
          uri: lb://TEXTCONTENT-SERVICE
          predicates:
            - Path=/textcontent-service/**
          filters:
            - CustomFilter
            - LoggingFilter
            - RemoveRequestHeader=Cookie
            - RewritePath=/textcontent-service/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh

logging:
  level:
    com.roy.spring.cloud.gateway: DEBUG

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /user-service/v3/api-docs
        name: user Service
      - url: /textcontent-service/v3/api-docs
        name: textcontent Service