spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.143.36:3306/hobby_user?useSSL=false&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: hobbyhobby
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true