spring:
  cloud:
    function:
      definition: userCached;
    stream:
      bindings:
        userCached-out-0:
          destination: allUser
        userCached-in-0:
          destination: allUser
        user-out-0:
          destination: textContent
        user-out-1:
          destination: photoContent
        user-out-2:
          destination: community
      rabbit:
        bindings:
          userCached-out-0:
            producer:
              exchangeType: direct
              routing-key: UserCached
          userCached-in-0:
            consumer:
              exchangeType: direct
              binding-routing-key: UserCached
          user-out-0:
            producer:
              exchangeType: direct
              routing-key: User
          user-out-1:
            producer:
              exchangeType: direct
              routing-key: User
          user-out-2:
            producer:
              exchangeType: direct
              routing-key: User
  rabbitmq:
    host: 52.79.143.36
    username: root
    password: root
    port: 5672
