spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.143.36:3306/hobby_imageServer?useSSL=false&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: hobbyhobby
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate:
        default_batch_fetch_size: 10
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:schema.sql