spring:
  cloud:
    function:
      definition: user;
    stream:
      bindings:
        photoContent-out-0:
          destination: community
        user-in-0:
          destination: photoContent
      rabbit:
        bindings:
          photoContent-out-0:
            producer:
              exchangeType: direct
              routing-key: PhotoContent
          user-in-0:
            consumer:
              exchangeType: direct
              binding-routing-key: User
  rabbitmq:
    host: 52.79.143.36
    username: root
    password: root
    port: 5672
