spring:
  cloud:
    function:
      definition: user;
    stream:
      bindings:
        user-in-0:
          destination: textContent
        userCached-out-0:
          destination: allTextContent
        userCached-in-0:
          destination: allTextContent
      rabbit:
        bindings:
          userCached-out-0:
            producer:
              exchangeType: direct
              routing-key: UserCached
          userCached-in-0:
            consumer:
              exchangeType: direct
              binding-routing-key: UserCached
          user-in-0:
            consumer:
              exchangeType: direct
              binding-routing-key: User
  rabbitmq:
    host: 52.79.143.36
    username: root
    password: root
    port: 5672
